language: python
cache: pip

python:
  - '3.7'

env:
  global:
    - secure: "US0I3nlyyWqQr3I4F2SVW8oARdDdfAgJnY4Q3fDTiLXYTNqMFZ59GfTEvwUP6Jpv/o4Nq91TAWOp0nJ58Hg5yJXo4zXr3VFAlXooHbgHf+DAwJRECdwAkCI9HbFJhbSzaqTt5EsHOEgTNJ2WUTY/EYk458+TKhtMQH6Imt8edUHaiM0vePWc+gmGgy82TYN7Heq2aI0OPl9aESJIx994S4vhFs0/On+HnDO++1sreQUaGX33ms2v04KZARBk7m3NFeLJrbdR0b2aK2kHAAkTVEWp4cu5aONdDlCytiTD9rca757j0StyevxE3OBkWs5PV04lNZ1SslkmMlKBAlpLX8skmxJsE+LxjyDLku6FbqFECXWjNjwjtHLUQd9+Q1RpcpP6iEFZVgzeNfYfm2bT/t49wFyTz3/PTAuxdlQW8EYpUTM1MQxDlBHImdBQTFPM7U975l1sgzE8Gia7KsMrifU/x3X6SLsH6jsXTt3lEzLEYtY7pkG2xmkZFQZYAXsR1smkXiIlwuJYxjxWEINEQnsqHd5Vr4JVgcyOuik96N/VxBc95F3Hqjc89NeM+cKq+qchKZmuebmFuXNyFT04lIGToWZgZKT+Yt2FEhpzsuz9InpSuvF+XlxGAo1i7W5vcHFoM8Ovna8ExAc1itz+uysyIy9Ro91WxuBadRvDjFg="
    - SPHINX_DIR=docs/sphinx
    - HTML_DIR=docs/sphinx/_build/html

install:
  - pip install --upgrade sphinx sphinx-sitemap

script:
  # touch .nojekyll else github-pages messes up theme
  - make -C ${SPHINX_DIR} html && touch ${HTML_DIR}/.nojekyll

deploy:
  # stuff related to deploying to gh-pages
  # GH_TOKEN is set in env:global:secure
  provider: pages
  strategy: git
  cleanup: false
  token: $GH_TOKEN
  on:
    branch: master
    python: "3.7"
  local_dir: ${HTML_DIR}
  project_name: SPIDAL-MDAnalysis-Midas-tutorial
  # use dpl v2
  edge: true
